### ISSUE TITLE
error ListView and TypeError

### ISSUE THREAD

**Issue by z4q** [Vivify-Ideas/expo-boilerplate#22]
![Screenshot 2019-06-12 at 09 33 09 AM](https://user-images.githubusercontent.com/4398119/59317385-37a5ce00-8cf5-11e9-8b9a-d3bcf502d4ad.png)

got error 
Warning: ListView is deprecated and will be removed in a future release. See https://fb.me/nolistview for more information

and 
TypeError: TypeError: _i18n.default.t is not a function. (In '_i18n.default.t('auth.offline')', '_i18n.default.t' is undefined)

**Comment by AlexSensei** [comment]
@z4q I've fixed the issue with `i18n` and as for the `ListView`, it's the `KeyboardAwareScrollView` library that we used to wrap screens, we will change it in the future, but for now if you need a fix just change all the `KeyboardAwareScrollView` to `ScrollView`
