### ISSUE TITLE
Unable to resolve module `i18n`

### ISSUE THREAD

**Issue by waqarkhan327** [Vivify-Ideas/expo-boilerplate#33]
Unable to resolve module `i18n` when running the command `expo build:android -t apk`.
It is working fine when running the app normally, instead of generating the apk.
Following is the command output.

expo build:android -t apk

Starting Metro Bundler on port 19001.
Successfully ran `adb reverse`. Localhost URLs should work on the connected Android device.
Tunnel ready.
Publishing to channel 'default'...
Building iOS bundle
Unable to resolve module `i18n` from `C:\Users\Users\Downloads\Compressed\expo-boilerplate-master\components\shared\modal\PasswordChangeModal.js`: Module `i18n` does not exist in the Haste module map

**Comment by farazirfan47** [comment]
Getting same issue

**Comment by farazirfan47** [comment]
I have fixed it by changing the import statement from:
import $t from 'i18n';
To
import $t from 'i18n-js';

**Comment by AlexSensei** [comment]
@waqarkhan327 sorry for not answering for so long, the issue was, the module resolver was set to work only in dev :) enable it in prod and it will work fine :)
